# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: coinfloor 0.4.0 ruby lib

Gem::Specification.new do |s|
  s.name = "coinfloor"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Vadim Marchenko"]
  s.date = "2014-03-09"
  s.description = "Ruby API for use with coinfloor."
  s.email = "vadim@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".rspec",
    ".ruby-gemset",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "coinfloor.gemspec",
    "lib/coinfloor.rb",
    "lib/coinfloor/collection.rb",
    "lib/coinfloor/helper.rb",
    "lib/coinfloor/model.rb",
    "lib/coinfloor/net.rb",
    "lib/coinfloor/orders.rb",
    "lib/coinfloor/ticker.rb",
    "lib/coinfloor/transactions.rb"
  ]
  s.homepage = "https://github.com/cryptopay-dev/coinfloor-ruby"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.11"
  s.summary = "Coinfloor Ruby API"

end

